---  
- name: Download openempi
  get_url: dest=/tmp url=https://kenai.com/projects/openempi/downloads/download/openempi-2.2.7-openempi.tar.gz

- name: extract openempi to /opt
  command: chdir=/opt creates=/opt/openempi-2.2.7 tar xzf /tmp/openempi-2.2.7-openempi.tar.gz -C /opt
