---  
- name: Download openempi
  get_url: dest=/tmp url=https://kenai.com/projects/openempi/downloads/download/openempi-{{ openempi_version }}-openempi.tar.gz

- name: extract openempi to /opt
  command: chdir=/opt creates=/opt/openempi-{{ openempi_version }} tar xzf /tmp/openempi-{{ openempi_version }}-openempi.tar.gz -C /opt

- name: Insert jdbc.properties
  template: src=jdbc.properties dest=/opt/openempi-{{ openempi_version }}/conf

- name: Insert mpi-config.xml
  file: path=/opt/openempi-{{ openempi_version }}/conf/mpi-config.xml src=mpi-config.xml owner=tomcat7 group=tomcat7

- name: Set permissions on openempi directory to tomcat
  file: path=/opt/openempi-{{ openempi_version }} owner=tomcat7 group=tomcat7 recurse=yes state=directory

- name: Deploy war and rename to openempi-admin.war
  command: cp /opt/openempi-{{ openempi_version }}/openempi-webapp-web-{{ openempi_version }}.war /var/lib/tomcat7/webapps/openempi-admin.war

- name: Set permissions on war file
  file: path=/var/lib/tomcat7/webapps/openempi-admin.war owner=tomcat7 group=tomcat7

- name: Create fileRepository directory
  file: path=/var/lib/tomcat7/fileRepository owner=tomcat7 group=tomcat7 recurse=yes state=directory

