---  
- name:  Install Tomcat
  apt: name={{ item }} state=installed
  with_items:
    - tomcat7

- name: Configure tomcat to work with openempi
  template: src=tomcat7 dest=/etc/init.d/tomcat7 mode=0755 
  notify: Restart Tomcat

